/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ADC_Driver.h"
#include "I2C_Driver.h"
#include "PCA_Driver.h"
#include "NVIC_Driver.h"
#include "SYSCFG_Driver.h"
#include "Button_Driver.h"
#include "led_Driver.h"
#include "I2C2_Driver.h"
#include "PCA2_Driver.h"


volatile uint8_t Mode = 0;
volatile uint8_t ledState = 0;
volatile uint8_t BLinkState = 0;

static uint16_t x_angle = 90;
static uint16_t y_angle = 90;


void Left_Control(uint16_t x_value,uint16_t y_value){

   if(x_value > 3800  ){

	   if(x_angle < 180)
		   x_angle++;

   }
   else if(x_value < 200){

	   if(x_angle > 0)
		   x_angle--;

   }



   if(y_value > 3800 ){

	   if(y_angle < 180)
		   y_angle++;
   }

   else if(y_value < 200){

	   if(y_angle > 0)
		   y_angle--;
   }

   servo2_angle(0, x_angle);
   servo2_angle(1, y_angle);

}

void Both_Control(uint16_t x_value,uint16_t y_value){


   if(x_value > 3800){

	   if(x_angle < 180)
		   x_angle++;

   }
   else if(x_value < 200){

	   if(x_angle > 0)
		   x_angle--;

   }

   if(y_value > 3800){

	   if(y_angle < 180)
		   y_angle++;
   }

   else if(y_value < 200){

	   if(y_angle > 0)
		   y_angle--;
   }

   servo_angle(0, x_angle);
   servo_angle(1, y_angle);
   servo2_angle(0, x_angle);
   servo2_angle(1, y_angle);

}


void Right_Control(uint16_t x_value,uint16_t y_value)
{

   if(x_value > 3800 ){

	   if(x_angle < 180)
		   x_angle++;

   }
   else if(x_value < 200){

	   if(x_angle > 0)
		   x_angle--;

   }



   if(y_value > 3800){

	   if(y_angle < 180)
		   y_angle++;
   }

   else if(y_value < 200){

	   if(y_angle > 0)
		   y_angle--;
   }

   servo_angle(0, x_angle);
   servo_angle(1, y_angle);
}


int main(void)
{

  ADC1_GPIO_Init();
  ADC1_Init();
  Button_Init();
  I2C_GPIO_Init();
  I2C_Init();
  I2C2_GPIO_Init();
  I2C2_Init();
  PCA_Init();
  PCA2_Init();
  LED_Init();


  uint16_t x_value;
  uint16_t y_value;


  NVIC_EnableIRQ(EXTI3_IRQn);
  servo_angle(0, 90);
  servo_angle(1, 90);
  servo2_angle(0, 90);
  servo2_angle(1, 90);



  while(1){
    	y_value = ADC1_Read(0);
    	x_value = ADC1_Read(1);





    		  switch(Mode){

    		  case 1:
    			  Left_Control(x_value, y_value);
    			  LED_Green_On();
    			  LED_WhiteOff();
    			  LED_Blue_Off();
    			  break;

    		  case 2:
    			  Both_Control(x_value, y_value);
    			  LED_Green_Off();
    			  LED_White_On();
    			  LED_Blue_Off();
    			  break;

    		  case 3:
    			  Right_Control(x_value, y_value);
    			  LED_Green_Off();
    			  LED_WhiteOff();
    			  LED_Blue_On();
    			  break;

    		  default:
    			  LED_Green_Off();
    			  LED_WhiteOff();
    			  LED_Blue_Off();
    			  break;
    	      }


//    		  if(BLinkState){
//
//    			  PCA_SetPWM(4, 0, 0);
//    			  PCA_SetPWM(5, 0, 0);
//
//    			  delay_ms(500);
//
//    			  PCA_SetPWM(5, 0, 4095);
//    			  PCA_SetPWM(4, 0, 4095);
//
//    		  }
//
//
//    		  if(ledState){
//
//
//    			        PCA_SetPWM(4, 0, 4095);
//    			        PCA_SetPWM(5, 0, 4095);
//
//    		  }
//
//		        else{
//			      PCA_SetPWM(4, 0, 0);
//			      PCA_SetPWM(5, 0, 0);
//		        }


    }

}


void EXTI2_IRQHandler()
{

	if(EXTI_isPending(2))
	{
		EXTI_ClearPending(2);

		ledState = !ledState;
	}


}

void EXTI3_IRQHandler()
{
	if(EXTI_isPending(3)){

		EXTI_ClearPending(3);

		Mode++;



		if (Mode > 3)
			Mode = 1;
	}

}


void EXTI4_IRQHandler()
{

	if(EXTI_isPending(4)){

		EXTI_ClearPending(4);

		BLinkState = !BLinkState;
	}

}

